### ISSUE TITLE
Reschedule an appointment: Changing the date

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#74]
Name: Rescheduling the date
Date: Jan 9, 2021
Description: An error pop-up appears before even finishing to enter the date. The date must be entered in the order of month, year, day for it to work. The error message is also incorrect when attempting to enter a date in the past.

Steps to Reproduce:
1. localhost:3001
2. Login
3. Reschedule an appointment
4. Change date

![image](https://user-images.githubusercontent.com/74369428/104091175-bdfe0980-52b6-11eb-80eb-4bae8fb30e94.png)
![image](https://user-images.githubusercontent.com/74369428/104091184-cce4bc00-52b6-11eb-8f8f-ecfd3bb2cf19.png)

**Comment by okaystephen** [comment]
Fixed; forces user to to use the calendar interface instead of typing the date
![Screen Shot 2021-01-12 at 4 56 38 PM](https://user-images.githubusercontent.com/44962445/104292170-74e8c800-54f7-11eb-9318-1fa99e8f0662.png)
![Screen Shot 2021-01-12 at 4 56 54 PM](https://user-images.githubusercontent.com/44962445/104292175-75815e80-54f7-11eb-947c-10e240013190.png)
![Screen Shot 2021-01-12 at 4 57 02 PM](https://user-images.githubusercontent.com/44962445/104292178-76b28b80-54f7-11eb-9bcc-03a24f42a66a.png)
